### ISSUE TITLE
Running testflo on script, even when called with full path, runs a different script

### ISSUE THREAD

**Issue by hschilling** [OpenMDAO/testflo#103]
I was having issues with which version of a library (aviary) I was working on was installed, but even when I pointed at an aviary test script with a full path, testflo would not run the same script as when running the script with just python.

So, for example, I intentionally put a bad import in the first line of 

/Users/hschilli/Documents/OpenMDAO/dev/I29-handle-wrong-script-name/aviary/interface/test/test_simple_mission.py

When I ran that script with python, I got the error

```
$ python /Users/hschilli/Documents/OpenMDAO/dev/I29-handle-wrong-script-name/aviary/interface/test/test_simple_mission.py
Traceback (most recent call last):
  File "/Users/hschilli/Documents/OpenMDAO/dev/I29-handle-wrong-script-name/aviary/interface/test/test_simple_mission.py", line 1, in <module>
    import osqq
ModuleNotFoundError: No module named 'osqq'
```

But when I ran the same script using testflo, there were no errors. It was apparently running the code from another directory that was checked out to a different branch.

**Comment by swryan** [comment]
If I understood correctly, from the Slack conversation, this issue was related to pip installing OpenMDAO with -e from different file system locations... so `pip install -e  /location1/openmdao` followed later by `pip install -e /location2/openmdao`, which resulted in multiple entries in your `easy-install.path`
```
In case anyone else runs into this, I kept getting problems where I would import openmdao and I would get a version from another directory that I had used previously! I did a lot of things, but the problem turned out to be that in the easy-install.pth file there was a line
/Users/hschilli/Documents/OpenMDAO/dev/I3060-mod-reports
and I kept importing that one. I just had to delete that line and all is well. 
```
If that's the case I think we can close this issue?

**Comment by swryan** [comment]
Closing this based on the last comment
