### ISSUE TITLE
License file in pypi archive

### ISSUE THREAD

**Issue by toddrme2178** [OpenMDAO/testflo#14]
The pypi source archive isn't including the `LICENSE.txt` file. Would it be possible to add it? It is very helpful when packaging this for Linux distributions. Thank you.

**Comment by kmarsteller** [comment]
Sorry, I didn't see this for a while. This has just been added to 1.3.0 today.

**Comment by swryan** [comment]
I think this was taken care of. 
Closing issue...  Let us know if you need anything else.
