### ISSUE TITLE
Output test results to standard formats

### ISSUE THREAD

**Issue by nwu63** [OpenMDAO/testflo#69]
One useful feature would be for testflo to output the test results using some sort of standard format, say the JUnitXML format that pytest also supports (and readable by CI services such as Azure Pipelines).

**Comment by nwu63** [comment]
No worries, I'll close the issue then.

**Comment by JustinSGray** [comment]
is there a format specification somewhere I could take a look at?

**Comment by nwu63** [comment]
Yeah that looks right, though it seems that pytest just uses their own writer [here](https://docs.pytest.org/en/7.1.x/_modules/_pytest/junitxml.html). This new feature may be difficult to implement/support, I just thought I'd mention it here since I discovered that there are CI tools such as Jenkins/Azure that will read these outputs and generate some nice tables. The lab may move away from Azure in the future anyways so this is probably not even a "nice to have" feature for us.
